markdown: kramdown
highlighter: rouge


kramdown:
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
#gauges_id: 503c5af6613f5d0f19000027
#google_analytics_id: UA-50755011-1
#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/codenvy/codenvy
#help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true
  tutorials:
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Codenvy Docs
description: Cloud workspaces for development teams
url: https://codenvy.com

twitter:
  username: codenvyhq

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
#  - jekyll-mentions
#  - jekyll-avatar
#  - jekyll-seo-tag
#  - jemoji

exclude:
  - /dev/
  - README.md
  - .gitignore
  - docs.sh
  - assembly/*
  - _site/*
  - pom.xml
